---
label: Site configuration
hide_body: true
fields:
- type: text
  name: title
  label: Title
  description: Site title
  config:
    required: true
- type: file
  name: favicon
  label: Favicon
  description: A square icon that represents your website
- type: text
  name: description
  label: Site description
  description: The default site description used in meta data
- type: select
  name: layout
  label: Layout
  description: The layout of the site
  default: full-width
  config:
    required: true
    source:
      type: custom
    options:
    - full-width
    - boxed
- type: select
  name: style
  label: Style
  description: The style of the site
  default: classic
  config:
    required: true
    source:
      type: custom
    options:
    - minimal
    - classic
    - bold
- type: select
  name: palette
  label: Palette
  description: The palette of the site
  default: blue
  config:
    required: true
    source:
      type: custom
    options:
    - blue
    - green
    - red
    - gray
- type: select
  name: mode
  label: Mode
  description: The color scheme of the site
  default: dark
  config:
    required: true
    source:
      type: custom
    options:
    - light
    - dark
- type: select
  name: base_font
  label: Font
  default: sans-serif
  config:
    required: true
    source:
      type: custom
    options:
    - sans-serif
    - serif
- type: field_group
  name: header
  label: Header configuration
  fields:
  - type: include
    name: include_header
    label: Header configuration
    template: header
- type: field_group
  name: footer
  label: Footer configuration
  fields:
  - type: include
    name: include_footer
    label: Footer configuration
    template: footer
pages:
- site-metadata.json
